# Generated by Django 6.0.6 on 2026-06-06 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuestbookEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100, verbose_name='Имя автора')),
                ('author_email', models.EmailField(max_length=254, verbose_name='Email автора')),
                ('content', models.TextField(verbose_name='Текст записи')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('status', models.CharField(choices=[('active', 'Активно'), ('blocked', 'Заблокировано')], default='active', max_length=10, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Запись в гостевой книге',
                'verbose_name_plural': 'Записи в гостевой книге',
                'ordering': ['-created_at'],
            },
        ),
    ]
